<?php

declare(strict_types=1);

namespace Vortos\Messaging\Bus\Stamp;

use Symfony\Component\Messenger\Stamp\StampInterface;

/**
 * Carries the unique event ID through the Symfony Messenger envelope.
 * Used by IdempotencyMiddleware to detect duplicate processing.
 * Generated by EventBus on dispatch if not already present.
 */
final readonly class EventIdStamp implements StampInterface
{
    public function __construct(
        public string $eventId
    ){
    }
}